name: Update the pangolin sha string
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  update_pangolin_commit:
    name: Update pangolinstring
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - run: git submodule update --init --recursive
        name: Checkout submodules
      - uses: subosito/flutter-action@v1
        name: Prepare Flutter SDK
      - run: flutter channel dev
        name: Switch Flutter channel
      - run: flutter pub get
        name: Get dependencies
      - run: dart bin/update_pangolin_commit.dart
        name:  Update pangolinstring